import type {
  Coordinate,
  DailyEldEvent,
  DailyEldLog,
  DutyStatus,
  TimelineEvent,
  TripRequest,
  TripResponse,
} from '../types/trip'

const currentCoordinate: Coordinate = [-87.6298, 41.8781]
const pickupCoordinate: Coordinate = [-87.9065, 43.0389]
const fuelCoordinate: Coordinate = [-93.265, 38.9917]
const restCoordinate: Coordinate = [-94.5786, 38.9517]
const dropoffCoordinate: Coordinate = [-96.797, 32.7767]

const timeline: TimelineEvent[] = [
  {
    type: 'DRIVING',
    status: 'DRIVING',
    start_time: '2026-07-21T08:00:00Z',
    end_time: '2026-07-21T09:30:00Z',
    duration_minutes: 90,
    duration_hours: 1.5,
    location: 'Between Chicago, IL and Milwaukee, WI',
    coordinate: pickupCoordinate,
    distance_miles: 92,
    description: 'Driving toward pickup location',
  },
  {
    type: 'PICKUP',
    status: 'ON_DUTY_NOT_DRIVING',
    start_time: '2026-07-21T09:30:00Z',
    end_time: '2026-07-21T10:30:00Z',
    duration_minutes: 60,
    duration_hours: 1,
    location: 'Milwaukee, WI',
    coordinate: pickupCoordinate,
    distance_miles: null,
    description: 'Loading at pickup location',
  },
  {
    type: 'DRIVING',
    status: 'DRIVING',
    start_time: '2026-07-21T10:30:00Z',
    end_time: '2026-07-21T17:00:00Z',
    duration_minutes: 390,
    duration_hours: 6.5,
    location: 'Between Milwaukee, WI and Dallas, TX',
    coordinate: fuelCoordinate,
    distance_miles: 650,
    description: 'Driving toward drop-off location',
  },
  {
    type: 'FUEL',
    status: 'ON_DUTY_NOT_DRIVING',
    start_time: '2026-07-21T17:00:00Z',
    end_time: '2026-07-21T17:30:00Z',
    duration_minutes: 30,
    duration_hours: 0.5,
    location: 'Along route to Dallas, TX',
    coordinate: fuelCoordinate,
    distance_miles: null,
    description: 'Fuel stop 1',
  },
  {
    type: 'DRIVING',
    status: 'DRIVING',
    start_time: '2026-07-21T17:30:00Z',
    end_time: '2026-07-21T20:30:00Z',
    duration_minutes: 180,
    duration_hours: 3,
    location: 'Between Milwaukee, WI and Dallas, TX',
    coordinate: restCoordinate,
    distance_miles: 180,
    description: 'Driving toward drop-off location',
  },
  {
    type: 'DAILY_REST',
    status: 'SLEEPER_BERTH',
    start_time: '2026-07-21T20:30:00Z',
    end_time: '2026-07-22T06:30:00Z',
    duration_minutes: 600,
    duration_hours: 10,
    location: 'Along route to Dallas, TX',
    coordinate: restCoordinate,
    distance_miles: null,
    description: '10-hour sleeper-berth rest',
  },
  {
    type: 'DRIVING',
    status: 'DRIVING',
    start_time: '2026-07-22T06:30:00Z',
    end_time: '2026-07-22T13:00:00Z',
    duration_minutes: 390,
    duration_hours: 6.5,
    location: 'Between Milwaukee, WI and Dallas, TX',
    coordinate: dropoffCoordinate,
    distance_miles: 128.5,
    description: 'Driving toward drop-off location',
  },
  {
    type: 'DROPOFF',
    status: 'ON_DUTY_NOT_DRIVING',
    start_time: '2026-07-22T13:00:00Z',
    end_time: '2026-07-22T14:00:00Z',
    duration_minutes: 60,
    duration_hours: 1,
    location: 'Dallas, TX',
    coordinate: dropoffCoordinate,
    distance_miles: null,
    description: 'Unloading at drop-off location',
  },
]

const makeDailyEvent = (
  event: TimelineEvent,
  startMinute: number,
  endMinute: number,
  startTime: string,
  endTime: string,
  isoStart: string,
  isoEnd: string,
): DailyEldEvent => ({
  type: event.type,
  status: event.status,
  start_minute: startMinute,
  end_minute: endMinute,
  start_time: startTime,
  end_time: endTime,
  iso_start_time: isoStart,
  iso_end_time: isoEnd,
  duration_minutes: endMinute - startMinute,
  duration_hours: (endMinute - startMinute) / 60,
  location: event.location,
  description: event.description,
  coordinate: event.coordinate,
})

const fillEvent = (
  startMinute: number,
  endMinute: number,
  startTime: string,
  endTime: string,
  isoStart: string,
  isoEnd: string,
  description: string,
): DailyEldEvent => ({
  type: 'OFF_DUTY_FILL',
  status: 'OFF_DUTY',
  start_minute: startMinute,
  end_minute: endMinute,
  start_time: startTime,
  end_time: endTime,
  iso_start_time: isoStart,
  iso_end_time: isoEnd,
  duration_minutes: endMinute - startMinute,
  duration_hours: (endMinute - startMinute) / 60,
  location: null,
  description,
  coordinate: null,
})

const dailyLogs: DailyEldLog[] = [
  {
    date: '2026-07-21',
    events: [
      fillEvent(
        0,
        480,
        '00:00',
        '08:00',
        '2026-07-21T00:00:00Z',
        '2026-07-21T08:00:00Z',
        'Off duty before trip start',
      ),
      makeDailyEvent(
        timeline[0],
        480,
        570,
        '08:00',
        '09:30',
        timeline[0].start_time,
        timeline[0].end_time,
      ),
      makeDailyEvent(
        timeline[1],
        570,
        630,
        '09:30',
        '10:30',
        timeline[1].start_time,
        timeline[1].end_time,
      ),
      makeDailyEvent(
        timeline[2],
        630,
        1020,
        '10:30',
        '17:00',
        timeline[2].start_time,
        timeline[2].end_time,
      ),
      makeDailyEvent(
        timeline[3],
        1020,
        1050,
        '17:00',
        '17:30',
        timeline[3].start_time,
        timeline[3].end_time,
      ),
      makeDailyEvent(
        timeline[4],
        1050,
        1230,
        '17:30',
        '20:30',
        timeline[4].start_time,
        timeline[4].end_time,
      ),
      makeDailyEvent(
        timeline[5],
        1230,
        1440,
        '20:30',
        '24:00',
        timeline[5].start_time,
        '2026-07-22T00:00:00Z',
      ),
    ],
    status_totals: {
      off_duty_minutes: 480,
      sleeper_berth_minutes: 210,
      driving_minutes: 660,
      on_duty_not_driving_minutes: 90,
      off_duty_hours: 8,
      sleeper_berth_hours: 3.5,
      driving_hours: 11,
      on_duty_not_driving_hours: 1.5,
      total_minutes: 1440,
      total_hours: 24,
    },
  },
  {
    date: '2026-07-22',
    events: [
      makeDailyEvent(
        timeline[5],
        0,
        390,
        '00:00',
        '06:30',
        '2026-07-22T00:00:00Z',
        timeline[5].end_time,
      ),
      makeDailyEvent(
        timeline[6],
        390,
        780,
        '06:30',
        '13:00',
        timeline[6].start_time,
        timeline[6].end_time,
      ),
      makeDailyEvent(
        timeline[7],
        780,
        840,
        '13:00',
        '14:00',
        timeline[7].start_time,
        timeline[7].end_time,
      ),
      fillEvent(
        840,
        1440,
        '14:00',
        '24:00',
        '2026-07-22T14:00:00Z',
        '2026-07-23T00:00:00Z',
        'Off duty after trip completion',
      ),
    ],
    status_totals: {
      off_duty_minutes: 600,
      sleeper_berth_minutes: 390,
      driving_minutes: 390,
      on_duty_not_driving_minutes: 60,
      off_duty_hours: 10,
      sleeper_berth_hours: 6.5,
      driving_hours: 6.5,
      on_duty_not_driving_hours: 1,
      total_minutes: 1440,
      total_hours: 24,
    },
  },
]

const routeCoordinates: Coordinate[] = [
  currentCoordinate,
  [-87.7, 42.24],
  pickupCoordinate,
  [-89.4012, 43.0731],
  [-91.5302, 41.6611],
  [-93.6091, 41.6005],
  fuelCoordinate,
  restCoordinate,
  [-95.9928, 36.154],
  [-97.5164, 35.4676],
  [-97.3308, 32.7555],
  dropoffCoordinate,
]

export const calculateMockTrip = async (
  request: TripRequest,
): Promise<TripResponse> => {
  await new Promise((resolve) => window.setTimeout(resolve, 850))

  const locations = {
    current: {
      label: request.current_location,
      coordinate: currentCoordinate,
    },
    pickup: {
      label: request.pickup_location,
      coordinate: pickupCoordinate,
    },
    dropoff: {
      label: request.dropoff_location,
      coordinate: dropoffCoordinate,
    },
  }

  return {
    trip_summary: {
      total_distance_miles: 1050.5,
      estimated_driving_hours: 17.5,
      total_trip_hours: 30,
      total_trip_days: 2,
      fuel_stop_count: 1,
      initial_cycle_used_hours: request.current_cycle_used_hours,
      final_cycle_used_hours: request.current_cycle_used_hours + 19,
    },
    locations,
    route: {
      type: 'LineString',
      coordinates: routeCoordinates,
    },
    route_legs: [
      {
        start_label: request.current_location,
        end_label: request.pickup_location,
        distance_miles: 92,
        duration_minutes: 90,
        geometry: routeCoordinates.slice(0, 3),
      },
      {
        start_label: request.pickup_location,
        end_label: request.dropoff_location,
        distance_miles: 958.5,
        duration_minutes: 960,
        geometry: routeCoordinates.slice(2),
      },
    ],
    stops: [
      {
        id: 'current',
        type: 'CURRENT',
        label: request.current_location,
        coordinate: currentCoordinate,
        arrival_time: '2026-07-21T08:00:00Z',
        departure_time: '2026-07-21T08:00:00Z',
        duration_minutes: 0,
      },
      {
        id: 'pickup',
        type: 'PICKUP',
        label: request.pickup_location,
        coordinate: pickupCoordinate,
        arrival_time: '2026-07-21T09:30:00Z',
        departure_time: '2026-07-21T10:30:00Z',
        duration_minutes: 60,
      },
      {
        id: 'fuel-1',
        type: 'FUEL',
        label: 'Fuel stop 1',
        coordinate: fuelCoordinate,
        arrival_time: '2026-07-21T17:00:00Z',
        departure_time: '2026-07-21T17:30:00Z',
        duration_minutes: 30,
      },
      {
        id: 'daily-rest-1',
        type: 'DAILY_REST',
        label: '10-hour sleeper-berth rest',
        coordinate: restCoordinate,
        arrival_time: '2026-07-21T20:30:00Z',
        departure_time: '2026-07-22T06:30:00Z',
        duration_minutes: 600,
      },
      {
        id: 'dropoff',
        type: 'DROPOFF',
        label: request.dropoff_location,
        coordinate: dropoffCoordinate,
        arrival_time: '2026-07-22T13:00:00Z',
        departure_time: '2026-07-22T14:00:00Z',
        duration_minutes: 60,
      },
    ],
    timeline,
    daily_logs: dailyLogs,
    assumptions: [
      'Property-carrying driver using the 70-hour/8-day cycle.',
      'The driver starts after completing ten consecutive hours off duty.',
      'Pickup and drop-off each take one hour.',
      'Fueling takes 30 minutes.',
      'Fueling is required at least once every 1,000 miles.',
    ],
  }
}

export const dutyStatusLabels: Record<DutyStatus, string> = {
  OFF_DUTY: 'Off duty',
  SLEEPER_BERTH: 'Sleeper berth',
  DRIVING: 'Driving',
  ON_DUTY_NOT_DRIVING: 'On duty',
}
